import { createContext, useContext, ReactNode, useState } from 'react';

type Language = 'en' | 'de' | 'fr' | 'es';

interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'header.language': 'Language',
    'header.theme': 'Theme',
    'header.authentication': 'Authentication',
    'header.login': 'Login',
    'header.logout': 'Logout',
    'header.profile': 'Profile',
    'header.openSource': 'We ❤️ Open Source',
    'header.termsOfUse': 'Terms of Use',
    'theme.dark': 'Dark',
    'theme.light': 'Light',
    'auth.welcome': 'Welcome',
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    // Chat panel
    'chat.subtitle': 'Retrieval-Augmented Generation over Scientific Knowledge Graphs',
    'chat.supportedQuestionTypes': 'Supported question types',
    'chat.demoDescription': 'This is a demo version of the Chat Assistant. Please read the information provided first to understand which types of questions are currently supported.',
    'chat.settings': 'Settings',
    'chat.supportedQuestionTypesTitle': 'Supported Question Types',
    'chat.close': 'Close',
    'chat.infoIntro': 'This demo is connected to a curated subset of the',
    'chat.infoFocused': 'focused on',
    'chat.softwareArchitecture': 'software architecture',
    'chat.infoResearch': 'research.',
    'chat.infoCurrentSupport': 'The system currently supports questions such as:',
    'chat.infoQ1': 'Questions about research findings and contributions in software architecture',
    'chat.infoQ2': 'Questions about emerging trends and comparisons across studies',
    'chat.infoQ3': 'Questions about replication packages, reusable datasets, and tool support',
    'chat.infoQ4': 'Questions that relate to specific papers or supplementary materials indexed in the knowledge graph',
    'chat.infoNote': 'Note:',
    'chat.infoNoteText': 'Questions outside the scope of the indexed knowledge graph may produce limited or no results.',
    'chat.infoExamples': 'Example questions include:',
    'chat.infoEx1': 'Which papers evaluate the property security and have input data available?',
    'chat.infoEx2': 'Which papers investigate architectural assumptions?',
    'chat.infoEx3': 'Which papers investigating architecture evolution have not used input data?',
    'chat.infoEx4': 'How many papers that discuss repeatability as a validity threat use interviews in their evaluation?',
    'chat.infoEx5': 'In how many publications is confirmability identified as a validity threat while focus groups are employed for evaluation?',
    'chat.gotIt': 'Got it',
    'chat.configSettings': 'Configuration Settings',
    'chat.retrievalStrategy': 'Retrieval Strategy',
    'chat.direct': 'Direct',
    'chat.vectorANN': 'Vector ANN',
    'chat.graph': 'Graph',
    'chat.traversal': 'Traversal',
    'chat.llmModel': 'LLM Model',
    'chat.numArtifacts': 'Number of research artifacts (papers and supplementary materials)',
    'chat.answerMode': 'Answer Generation Mode',
    'chat.answerModePartial': 'Partial Answers',
    'chat.answerModePartialDesc': 'Per-hub LLM synthesis',
    'chat.answerModeDirect': 'Direct',
    'chat.answerModeDirectDesc': 'All hubs → final answer',
    'chat.done': 'Done',
    'chat.startConversation': 'Start a conversation',
    'chat.retrievingAnswer': 'Retrieving answer...',
    'chat.step.input_validation': 'Validating input...',
    'chat.step.checking_instant_response': 'Checking instant response...',
    'chat.step.instant_response': 'Generating instant response...',
    'chat.step.retrieving': 'Searching knowledge graph...',
    'chat.step.preparing': 'Preparing research artifacts...',
    'chat.step.analyzing': 'Analyzing research artifacts...',
    'chat.step.generating': 'Generating final answer...',
    'chat.step.processing': 'Processing results...',
    'chat.step.saving': 'Saving to conversation...',
    'chat.topicEntityId': 'Topic Entity ID',
    'chat.topicEntityIdPlaceholder': 'Topic entity ID...',
    'chat.enterMessage': 'Enter your message...',
    'chat.sendMessage': 'Send message',
    'chat.send': 'Send',
    'sidebar.workspace': 'Workspace',
    'sidebar.closeSidebar': 'Close sidebar',
    'sidebar.expandSidebar': 'Expand sidebar',
    'sidebar.collapseSidebar': 'Collapse sidebar',
    'sidebar.newChat': 'New Chat',
    'sidebar.searchChats': 'Search chats',
    'sidebar.searchChatsPlaceholder': 'Search chats...',
    'sidebar.clearSearch': 'Clear search',
    'sidebar.history': 'History',
    'sidebar.noResults': 'No results found',
    'sidebar.connected': 'Connected',
    'sidebar.mockMode': 'Mock Mode',
    'sidebar.backendOffline': 'Backend Offline',
    'sidebar.backendInitializing': 'Backend is starting up...',
    'sidebar.checking': 'Checking...',
    'sidebar.clearChat': 'Clear Chat History',
    'sidebar.deleteChat': 'Delete Conversation',
    // Graph panel
    'graph.title': 'Retrieval Graph',
    'graph.directMode': 'Direct Retrieval Mode',
    'graph.graphMode': 'Graph Retrieval Mode',
    'graph.clickToView': 'Click on "View Graph" in a response',
    'graph.toViewGraph': 'to view the graph',
    'graph.downloadSvg': 'Download as SVG',
    'graph.resetGraph': 'Reset graph',
    'graph.zoomIn': 'Zoom in',
    'graph.zoomOut': 'Zoom out',
    'graph.searchPlaceholder': 'Search in the graph...',
    'graph.searchAriaLabel': 'Search nodes in the graph',
    'graph.clearSearch': 'Clear search',
    'graph.prevMatch': 'Previous match',
    'graph.nextMatch': 'Next match',
    'graph.clickForDetails': 'Click on a node or arrow to view details',
    'graph.nodes': 'Nodes',
    'graph.closeDetails': 'Close details',
    'graph.edge': 'Edge',
    'graph.from': 'From',
    'graph.to': 'To',
    'graph.clear': 'Clear',
    'graph.literal': 'Literal',
    'graph.resource': 'Resource',
    'graph.edgePrefix': 'Edge: ',
    'graph.nodeLabel': 'node: ',
    'graph.svgAriaPrefix': 'Knowledge graph with',
    'graph.svgAriaSuffix': 'nodes. Tab to navigate nodes and edges, Enter or Space to select, Escape to deselect.',
    'graph.selectedNode': 'Selected',
    'graph.selectedEdge': 'Selected edge:',
    'graph.fromLabel': 'from',
    'graph.toLabel': 'to',
    'graph.idLabel': 'ID:',
  },
  de: {
    'header.language': 'Sprache',
    'header.theme': 'Design',
    'header.authentication': 'Authentifizierung',
    'header.login': 'Anmelden',
    'header.logout': 'Abmelden',
    'header.profile': 'Profil',
    'header.openSource': 'Wir ❤️ Open Source',
    'header.termsOfUse': 'Nutzungsbedingungen',
    'theme.dark': 'Dunkel',
    'theme.light': 'Hell',
    'auth.welcome': 'Willkommen',
    'auth.login': 'Anmelden',
    'auth.logout': 'Abmelden',
    'auth.register': 'Registrieren',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    // Chat panel
    'chat.subtitle': 'Retrieval-Augmented Generation über wissenschaftliche Wissensgraphen',
    'chat.supportedQuestionTypes': 'Unterstützte Fragetypen',
    'chat.demoDescription': 'Dies ist eine Demo-Version des Chat-Assistenten. Bitte lesen Sie zuerst die bereitgestellten Informationen, um zu verstehen, welche Fragetypen derzeit unterstützt werden.',
    'chat.settings': 'Einstellungen',
    'chat.supportedQuestionTypesTitle': 'Unterstützte Fragetypen',
    'chat.close': 'Schließen',
    'chat.infoIntro': 'Diese Demo ist mit einer kuratierten Teilmenge des',
    'chat.infoFocused': 'mit Fokus auf',
    'chat.softwareArchitecture': 'Software-Architektur',
    'chat.infoResearch': 'Forschung verbunden.',
    'chat.infoCurrentSupport': 'Das System unterstützt derzeit Fragen wie:',
    'chat.infoQ1': 'Fragen zu Forschungsergebnissen und Beiträgen in der Software-Architektur',
    'chat.infoQ2': 'Fragen zu neuen Trends und Vergleichen zwischen Studien',
    'chat.infoQ3': 'Fragen zu Replikationspaketen, wiederverwendbaren Datensätzen und Tool-Unterstützung',
    'chat.infoQ4': 'Fragen, die sich auf bestimmte Artikel oder ergänzende Materialien im Wissensgraphen beziehen',
    'chat.infoNote': 'Hinweis:',
    'chat.infoNoteText': 'Fragen außerhalb des indizierten Wissensgraphen können zu begrenzten oder keinen Ergebnissen führen.',
    'chat.infoExamples': 'Beispielfragen:',
    'chat.infoEx1': 'Welche Artikel bewerten die Eigenschaft Sicherheit und haben Eingabedaten verfügbar?',
    'chat.infoEx2': 'Welche Artikel untersuchen architektonische Annahmen?',
    'chat.infoEx3': 'Welche Artikel, die Architekturevolution untersuchen, haben keine Eingabedaten verwendet?',
    'chat.infoEx4': 'Wie viele Artikel, die Wiederholbarkeit als Validitätsbedrohung diskutieren, verwenden Interviews bei der Bewertung?',
    'chat.infoEx5': 'In wie vielen Publikationen wird Bestätigbarkeit als Validitätsbedrohung identifiziert, während Fokusgruppen für die Bewertung eingesetzt werden?',
    'chat.gotIt': 'Verstanden',
    'chat.configSettings': 'Konfigurationseinstellungen',
    'chat.retrievalStrategy': 'Abrufstrategie',
    'chat.direct': 'Direkt',
    'chat.vectorANN': 'Vektor ANN',
    'chat.graph': 'Graph',
    'chat.traversal': 'Traversierung',
    'chat.llmModel': 'LLM-Modell',
    'chat.numArtifacts': 'Anzahl der Forschungsartefakte (Artikel und Zusatzmaterialien)',
    'chat.answerMode': 'Antwortgenerierungsmodus',
    'chat.answerModePartial': 'Teilantworten',
    'chat.answerModePartialDesc': 'LLM-Synthese pro Hub',
    'chat.answerModeDirect': 'Direkt',
    'chat.answerModeDirectDesc': 'Alle Hubs → Finalantwort',
    'chat.done': 'Fertig',
    'chat.startConversation': 'Gespräch beginnen',
    'chat.retrievingAnswer': 'Antwort wird abgerufen...',
    'chat.step.input_validation': 'Eingabe wird geprüft...',
    'chat.step.retrieving': 'Wissensgraph wird durchsucht...',
    'chat.step.preparing': 'Forschungsartefakte werden vorbereitet...',
    'chat.step.analyzing': 'Forschungsartefakte werden analysiert...',
    'chat.step.generating': 'Finale Antwort wird generiert...',
    'chat.step.processing': 'Ergebnisse werden verarbeitet...',
    'chat.step.saving': 'In Konversation gespeichert...',
    'chat.topicEntityId': 'Themenentitäts-ID',
    'chat.topicEntityIdPlaceholder': 'Themenentitäts-ID...',
    'chat.enterMessage': 'Nachricht eingeben...',
    'chat.sendMessage': 'Nachricht senden',
    'chat.send': 'Senden',
    'sidebar.workspace': 'Arbeitsbereich',
    'sidebar.closeSidebar': 'Seitenleiste schließen',
    'sidebar.expandSidebar': 'Seitenleiste erweitern',
    'sidebar.collapseSidebar': 'Seitenleiste einklappen',
    'sidebar.newChat': 'Neuer Chat',
    'sidebar.searchChats': 'Chats durchsuchen',
    'sidebar.searchChatsPlaceholder': 'Chats durchsuchen...',
    'sidebar.clearSearch': 'Suche löschen',
    'sidebar.history': 'Verlauf',
    'sidebar.noResults': 'Keine Ergebnisse gefunden',
    'sidebar.connected': 'Verbunden',
    'sidebar.mockMode': 'Demo-Modus',
    'sidebar.backendOffline': 'Backend offline',
    'sidebar.backendInitializing': 'Backend wird gestartet...',
    'sidebar.checking': 'Überprüfen...',
    'sidebar.clearChat': 'Chathistorie löschen',
    'sidebar.deleteChat': 'Konversation löschen',
    // Graph panel
    'graph.title': 'Abrufgraph',
    'graph.directMode': 'Direkter Abrufmodus',
    'graph.graphMode': 'Graph-Abrufmodus',
    'graph.clickToView': 'Klicken Sie auf "View Graph" in einer Antwort',
    'graph.toViewGraph': 'um den Graphen anzuzeigen',
    'graph.downloadSvg': 'Als SVG herunterladen',
    'graph.resetGraph': 'Graph zuruecksetzen',
    'graph.zoomIn': 'Vergrößern',
    'graph.zoomOut': 'Verkleinern',
    'graph.searchPlaceholder': 'Im Graphen suchen...',
    'graph.searchAriaLabel': 'Knoten im Graphen suchen',
    'graph.clearSearch': 'Suche löschen',
    'graph.prevMatch': 'Vorheriges Ergebnis',
    'graph.nextMatch': 'Nächstes Ergebnis',
    'graph.clickForDetails': 'Klicken Sie auf einen Knoten oder Pfeil, um Details anzuzeigen',
    'graph.nodes': 'Knoten',
    'graph.closeDetails': 'Details schließen',
    'graph.edge': 'Kante',
    'graph.from': 'Von',
    'graph.to': 'Zu',
    'graph.clear': 'Löschen',
    'graph.literal': 'Literal',
    'graph.resource': 'Ressource',
    'graph.edgePrefix': 'Kante: ',
    'graph.nodeLabel': 'Knoten: ',
    'graph.svgAriaPrefix': 'Wissensgraph mit',
    'graph.svgAriaSuffix': 'Knoten. Tab zum Navigieren, Enter oder Leertaste zum Auswählen, Escape zum Abwählen.',
    'graph.selectedNode': 'Ausgewählt',
    'graph.selectedEdge': 'Ausgewählte Kante:',
    'graph.fromLabel': 'von',
    'graph.toLabel': 'zu',
    'graph.idLabel': 'ID:',
  },
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language') as Language | null;
    return saved || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
